channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - notebook
  - pip
  - pip:
    - torch==1.13
    - torchmetrics==0.6.0
    - scvi-tools==0.13.0
    - umap-learn==0.5.3
    - scgen
